[package]
name = "vulkan-engine"
version = "0.1.1"
edition = "2024"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
glam = "0.32.1"
gpu-allocator = "0.28.0"
log = "0.4.29"
presser = "0.3.1"
simple_logger = "5.2.0"
thiserror = "2.0.20"
anyhow = "1.0.104"
winit = "0.30.13"

[build-dependencies]
ash = "0.38.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
roxmltree = "0.21.1"
